import unittest

from lib.HTMLTestRunner import HTMLTestRunner
from lib.request_process import HttpRequest
from lib.send_email import SendMail
from project.ad_admin.conf import ip

path='/api/schedule/situation/36'
request=HttpRequest(ip)
class TestScheduleQuery(unittest.TestCase):
    def test_schedule(self):
        rs=request.http_request(path=path,method='GET')
        print(rs.json())
        assert rs.status_code==200
        assert rs.json()['msg']=='success'

if __name__=='__main__':
    suite=unittest.TestSuite()
    tests=[TestScheduleQuery("test_schedule")]
    suite.addTests(tests)
    #sendmail=Send_email()
    sendmail=SendMail()
    with open('//Users//ln//Downloads//Test//project//ad_admin//report//AdHTMLReport.html', 'w')as f:
        runner = HTMLTestRunner(stream=f,
                                title='Ad Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)
        #sendmail.send_em("294714025@qq.com","payxsjuipioobihi","liuna468@sina.com")
        sendmail.send("294714025@qq.com","payxsjuipioobihi","294714025@qq.com")
